// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCye2gOZccfWTgvlIhdC4r4pueK5EUL-XY',
    appId: '1:877106905994:web:7d9d79f384b98b6a387e73',
    messagingSenderId: '877106905994',
    projectId: 'country-pairs',
    authDomain: 'country-pairs.firebaseapp.com',
    storageBucket: 'country-pairs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3VzUGQNFvDFztIhOmFwNTLnD3XrjUwiw',
    appId: '1:877106905994:android:62c939faf20ad26a387e73',
    messagingSenderId: '877106905994',
    projectId: 'country-pairs',
    storageBucket: 'country-pairs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3t_DRafGxD--3fqOigrvx1vVd4fl8K2Q',
    appId: '1:877106905994:ios:eb816ad88a56e416387e73',
    messagingSenderId: '877106905994',
    projectId: 'country-pairs',
    storageBucket: 'country-pairs.firebasestorage.app',
    iosBundleId: 'com.countrypairs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3t_DRafGxD--3fqOigrvx1vVd4fl8K2Q',
    appId: '1:877106905994:ios:b8fce349725f6c36387e73',
    messagingSenderId: '877106905994',
    projectId: 'country-pairs',
    storageBucket: 'country-pairs.firebasestorage.app',
    iosBundleId: 'com.example.pairsGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCye2gOZccfWTgvlIhdC4r4pueK5EUL-XY',
    appId: '1:877106905994:web:3fcd586508b882f6387e73',
    messagingSenderId: '877106905994',
    projectId: 'country-pairs',
    authDomain: 'country-pairs.firebaseapp.com',
    storageBucket: 'country-pairs.firebasestorage.app',
  );
}
